language: node_js
addons:
  apt:
    packages:
      - build-essential
before_install:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      wget "https://www.foundationdb.org/downloads/6.2.11/ubuntu/installers/foundationdb-clients_6.2.11-1_amd64.deb"
      sudo dpkg -i foundationdb-clients_6.2.11-1_amd64.deb
      wget "https://www.foundationdb.org/downloads/6.2.11/ubuntu/installers/foundationdb-server_6.2.11-1_amd64.deb"
      sudo dpkg -i foundationdb-server_6.2.11-1_amd64.deb
    else
      wget "https://www.foundationdb.org/downloads/6.2.11/macOS/installers/FoundationDB-6.2.11.pkg"
      sudo installer -pkg FoundationDB-6.2.11.pkg -target /
    fi
node_js:
  - '10'
  - '12'
  - '14'
os:
  - linux
  - osx
before_deploy:
  - ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
  - npm run prebuild
  - tar -cvf "$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .
deploy:
  provider: releases
  file: "$ARCHIVE_NAME"
  draft: false
  prerelease: true
  token:
    secure: PW/mhQqmH9odcQNub6rifH8fdawbeWXM5lPVk7lTiIzRPs/mPsythCJ4rCXwalh3+RgYII/uGPDHQfXFdzMYH0NzpxwVwam6cGl7m5FmJChVv/fyUfNDTR+5ZWMj/X8j6TMXlkOu8WqGYlpI67VsMRO0ctCM5Xb+QCXkMy//Ww19nnKBHutyQj/m6R9+w0vU16YVVVF8FkMDF2X3I/LVWBfeSny7EGM7++P9E+lhJ2G5FJzxZKsCQ1F2gbpxQ9Ynu25LYN0ViTm3w4tZaOFyPgOlGTXlSsslvf3rtZa7aXfPO66MunzkNtfusefx38z0psKZyQ1eEFVxi0H3jSSlndMwmGsjnb8iIfBl+GbJcknA+aHVIPUPzHyT8OvMjiD47hIkcKy/tfpCHAyprBKO+/gegvdPyJCLF5NK2LxH6HzDJbCIZDO92Clq+3btqXe2BIlk1wVDQ0ZhNk5vrPNB5FKaGEOm44IXW7PuD1+aEYbRtLSbvnTx0Cw2OfLleX8Y3NV/j+7jvk55dQTiMFZ5X/VEtBIVwbE2pDZSxbUNL1HDn8nACq5mmQ+SfSYCghUKFgW1bhIwyojLFgZD3xGL24M4WxrBlJ46UOLPPciLnpQS5FrFdZSK3NIgO7MHxJ/JOM641IrEdhGP8ebs/V7cSeEsFzV3d1KdjMI3OTXnMus=
  on:
    tags: true
    node: 14
  skip_cleanup: true
