build: false

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "Current"

configuration: Release
platform:
  - x64

install:
  - ps: (new-object net.webclient).DownloadFile('https://www.foundationdb.org/downloads/5.1.7/windows/installers/foundationdb-5.1.7-x64.msi', 'c:\foundationdb.msi')
  - ps: dir c:\foundationdb.msi
  - ps: msiexec /i c:\foundationdb.msi /quiet /passive /norestart /log install.log
  - ps: timeout 5
  - ps: type install.log
  - dir
  - dir "C:\Program Files"
  - set FOUNDATIONDB_INSTALL_PATH=C:\Program Files\foundationdb\
  - set PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - dir "%FOUNDATIONDB_INSTALL_PATH%"
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

after_test:
  - ps: If ($env:nodejs_version -eq "Current") { npm run prebuild }

artifacts:
  - path: prebuilds
    name: $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM)
    type: zip

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: true
    auth_token:
      secure: H4WQnwF6tvz1u0DhcIDTWF8GoVkioJFQMle/NiSpXNaLMqp1vkGRFcRIYwUd4jGH
    on:
      appveyor_repo_tag: true
      nodejs_version: "Current"
